import os
import uuid
import logging
from datetime import datetime
from pathlib import Path
from config import get_settings

logger = logging.getLogger(__name__)

INVOICE_DIR = Path(__file__).parent.parent / 'static' / 'invoices'
INVOICE_DIR.mkdir(parents=True, exist_ok=True)


INVOICE_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&display=swap');
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    font-family: 'DM Sans', sans-serif;
    background: #fff;
    color: #111;
    padding: 48px;
    max-width: 640px;
    margin: 0 auto;
  }}
  .header {{ display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 40px; }}
  .brand {{ font-size: 28px; font-weight: 800; letter-spacing: -0.5px; }}
  .brand span {{ color: #00C853; }}
  .badge {{
    display: inline-block; padding: 4px 12px; border-radius: 999px;
    background: #E8F5E9; color: #00C853; font-size: 12px; font-weight: 600;
    border: 1px solid #A5D6A7;
  }}
  .divider {{ border: none; border-top: 1px solid #E0E0E0; margin: 24px 0; }}
  .section-label {{ font-size: 11px; letter-spacing: 1.2px; text-transform: uppercase; color: #9E9E9E; margin-bottom: 6px; }}
  .value {{ font-size: 16px; font-weight: 500; color: #111; }}
  .grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 24px; margin: 24px 0; }}
  .amount-box {{
    background: #0A0F0A; color: #E8F5E9; border-radius: 14px;
    padding: 20px 24px; margin-top: 32px;
    display: flex; justify-content: space-between; align-items: center;
  }}
  .amount-box .label {{ font-size: 12px; letter-spacing: 1px; text-transform: uppercase; color: #7EA87E; }}
  .amount-box .total {{ font-size: 28px; font-weight: 700; color: #00C853; }}
  .footer {{ margin-top: 40px; font-size: 12px; color: #9E9E9E; text-align: center; }}
  .ref {{ font-family: monospace; font-size: 11px; color: #9E9E9E; }}
</style>
</head>
<body>
  <div class="header">
    <div class="brand">Y<span>A</span>RN</div>
    <span class="badge">INVOICE</span>
  </div>

  <div class="section-label">Invoice Number</div>
  <div class="value">#{invoice_number}</div>
  <div class="ref">Generated via YARN Voice Agent</div>

  <hr class="divider">

  <div class="grid">
    <div>
      <div class="section-label">Bill To</div>
      <div class="value">{client_name}</div>
    </div>
    <div>
      <div class="section-label">Date</div>
      <div class="value">{date}</div>
    </div>
  </div>

  <hr class="divider">

  <div class="section-label">Description of Work / Goods</div>
  <div class="value" style="margin-top: 4px; line-height: 1.6;">{description}</div>

  <div class="amount-box">
    <div>
      <div class="label">Total Amount Due</div>
      <div style="font-size:12px; color: #3D5C3D; margin-top: 3px;">Nigerian Naira (NGN)</div>
    </div>
    <div class="total">&#8358;{amount_formatted}</div>
  </div>

  <div class="footer">
    <p>Payment terms: Due on receipt &nbsp;·&nbsp; Generated by YARN Agent on {date}</p>
    <p style="margin-top: 6px;">This is a prototype invoice generated by YARN Voice Agent.</p>
  </div>
</body>
</html>"""


def generate_invoice(description: str, amount: int | float, client_name: str) -> dict:
    """
    Generate a PDF invoice using WeasyPrint and save it to static/invoices/.
    Returns the public URL and filename.
    """
    settings = get_settings()
    invoice_number = str(uuid.uuid4()).split('-')[0].upper()
    date = datetime.now().strftime('%d %B %Y')
    amount_formatted = f'{int(amount):,}'

    html = INVOICE_HTML.format(
        invoice_number=invoice_number,
        client_name=client_name or 'Valued Client',
        date=date,
        description=description,
        amount_formatted=amount_formatted,
    )

    filename = f'invoice-{invoice_number}.pdf'
    filepath = INVOICE_DIR / filename

    try:
        from weasyprint import HTML as WPHtml
        WPHtml(string=html, base_url=str(INVOICE_DIR)).write_pdf(str(filepath))
        url = f'{settings.BASE_URL}/static/invoices/{filename}'
        return {
            'success': True,
            'url': url,
            'filename': filename,
            'invoice_number': invoice_number,
            'simulated': False,
        }
    except Exception as exc:
        logger.error('WeasyPrint error: %s', exc)
        # Return a mock URL if PDF generation fails
        return {
            'success': True,
            'url': f'{settings.BASE_URL}/static/invoices/demo-invoice.pdf',
            'filename': 'demo-invoice.pdf',
            'invoice_number': invoice_number,
            'simulated': True,
        }
